import { StyleSheet, Dimensions, Platform } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const isWeb = Platform.OS === 'web';

export const styles = StyleSheet.create({
  cardsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginHorizontal: 12,
    marginBottom: 24,
    marginTop: 32, // Espaço do topo
  },
  cardBig: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 32,
    paddingHorizontal: 18,
    marginRight: 18,
    alignItems: 'flex-start',
    elevation: 2,
    minWidth: 220,
    maxWidth: 320,
  },
  cardLabelBig: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: isWeb ? 18 : 15,
    marginBottom: 8,
    textAlign: 'left',
  },
  cardValueBig: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: isWeb ? 28 : 20,
    textAlign: 'left',
  },
  movementsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 0,
    marginBottom: 8,
    marginTop: 8,
    backgroundColor: '#FFF',
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 8,
    color: '#171717',
  },
  monthPickerText: {
    marginLeft: 12,
    color: '#6567DD',
    fontWeight: 'bold',
    fontSize: 16,
  },
  transactionItemShadow: {
    backgroundColor: '#F0F4FF',
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 18,
    marginHorizontal: 8,
    alignItems: 'flex-start',
    // Sombra para iOS
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    // Sombra para Android
    elevation: 3,
  },
  badge: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minWidth: 70,
  },
  badgeText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    fontStyle: 'italic',
    textAlign: 'left',
  },
  transactionValueBelow: {
    color: '#171717',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'left',
    marginTop: 2,
    marginLeft: 2,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 24,
    width: 320,
    alignItems: 'center',
    elevation: 8,
  },
  modalContentCalendar: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    width: 340,
    alignItems: 'center',
    elevation: 8,
  },
  filterButton: {
    backgroundColor: '#6567DD',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginTop: 16,
    width: '90%',
    alignItems: 'center',
  },
  filterButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 18,
  },
  yearButton: {
    backgroundColor: '#F0F4FF',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginHorizontal: 4,
  },
  yearButtonSelected: {
    backgroundColor: '#6567DD',
  },
  monthButton: {
    backgroundColor: '#F0F4FF',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    margin: 4,
    minWidth: 80,
    alignItems: 'center',
  },
  monthButtonSelected: {
    backgroundColor: '#00B94A',
  },
  closeModalButton: {
    marginTop: 8,
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#F0F4FF',
  },
  cardsRowScroll: {
    marginBottom: 24,
    marginTop: 32,
    minHeight: 120,
  },
  cardBigSquare: {
    borderRadius: 4, // ainda mais quadrado
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginRight: 16,
    alignItems: 'flex-start',
    elevation: 2,
    width: isWeb ? 320 : 200, // maior no PC, menor no mobile
    minWidth: isWeb ? 260 : 150,
    maxWidth: isWeb ? 400 : 240,
    justifyContent: 'center',
  },
  cardLabelBigSquare: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 10,
    textAlign: 'left',
  },
  cardValueBigSquare: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'left',
  },
  movementsBlock: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingBottom: 18,
    paddingTop: 2,
    marginHorizontal: 8,
    marginTop: 8,
    marginBottom: 24,
    // Sombra leve para destacar
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
}); 